name: Build and Release Electron App

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: build and release electron app for win and macos

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install yarn
        run: npm install yarn -g

      - name: Install dependencies
        run: yarn

      - name: build windows app
        if: matrix.os == 'windows-latest'
        run: |
          yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build macos app
        if: matrix.os == 'macos-latest'
        run: |
          yarn electron:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: copy target files for win
        if: matrix.os == 'windows-latest'
        run: |
          robocopy "dist" "dist_p" *.exe
          robocopy "dist" "dist_p" *.msi
          return 0

      - name: copy target files for macos
        if: matrix.os == 'macos-latest'
        run: |
          rsync -av --include="*.dmg" --exclude="*" "dist/" "dist_p/"

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: dist_p

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist_p/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
